# Generated by Django 4.1.3 on 2022-11-23 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='product_name',
        ),
    ]
