# Generated by Django 4.1.3 on 2022-11-24 12:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('payment', '0002_rename_name_item_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('inclusive', models.BooleanField(default=False)),
                ('jurisdiction', models.CharField(choices=[('US', 'United States'), ('DE', 'Germany'), ('RU', 'Russia')], default='US', max_length=2)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.TextField(choices=[('usd', 'Dollars'), ('eur', 'Euro'), ('rub', 'Rubles')], default='usd'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(default='Basket', max_length=25)),
                ('total_amount', models.IntegerField(default=0)),
                ('currency', models.CharField(max_length=3)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percents', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount_name', models.CharField(max_length=255)),
                ('duration', models.CharField(default='forever', max_length=25)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payment.order'),
        ),
    ]
